### ISSUE TITLE
init cmd

### ISSUE THREAD

**Issue by cyanBone** [thomasvvugt/fiber-boilerplate#12]
初始化命令来创建项目
比如：
composer create-project laravel/laravel=5.4.* --prefer-dist ./

**compose create-project**

git clone 后还要删除.git/

--------------

.gitignore

.idea   // idea 文件   比如还有vscode .....
.DS_Store  // mac 文件
pkg/debug
pkg/releases/*
log/*.*
assets/upload

------------

打包和发布

Makefile

COMPILE_TIME = $(shell date +"%Y%m%d-%H%M%S")
GIT_REVISION = $(shell git show -s --pretty=format:%h)
run: build
	pkg/debug/debbug

build:
	go build -o pkg/debug/debbug

release:
	mkdir -p pkg/releases
	rm -rf releases
	GOOS=freebsd GOARCH=amd64 go build -ldflags "-s -w" -tags=jsoniter -o releases/videopro   //  releases 程序 最小 平台  优化
	cp -r config releases/config  //配置文件
	cp -r assets releases/assets  // css & js 
	cp -r templates releases/templates //  html tpl
	mkdir releases/log
	echo $(GIT_REVISION) > releases/VERSION   //git version
	tar -cvzf pkg/releases/releases-$(COMPILE_TIME).tar.gz releases/
	rm -rf releases

all: build run release

**Comment by cyanBone** [comment]
我的对你的项目不熟悉，所以不敢直接提交

**Comment by thomasvvugt** [comment]
Hi @cyanBone
Please open issues in English language.
Please note, the application is **not** installable through Composer, rather git clone of download the latest version.
