### ISSUE TITLE
Where return after c.Send ?

### ISSUE THREAD

**Issue by arkady-bagdasarov** [thomasvvugt/fiber-boilerplate#7]
I read about how to structure fiber project and saw this 
https://github.com/thomasvvugt/fiber-boilerplate/blob/155cd94b6dd241763db2bd7e9d27173edf495202/app/controllers/api/UserController.go#L15

Why after this string you didn't do return?
Because if you didn't do return from func your code will continue executing next, right?

**Comment by arkady-bagdasarov** [comment]
And also `c.Send()` method gets only one parameter. Please, correct me if i wrong.
https://github.com/gofiber/fiber/blob/master/ctx.go#L893

**Comment by thomasvvugt** [comment]
Hi @arkady-bagdasarov, this behavior was indeed updated in Fiber v2. I am planning on updating my repository soon™.

**Comment by JeffPHP** [comment]
> Hi @arkady-bagdasarov, this behavior was indeed updated in Fiber v2. I am planning on updating my repository soon™.

In cas it helps, I did a fork to V2 here : https://github.com/JeffPHP/fiber-gofiber-v2-boilerplate

**Comment by thomasvvugt** [comment]
See #9
